name: microcms

on:
  workflow_dispatch:
  repository_dispatch:
    types: [updata]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    env:
      REPO: https://kentaro19781123:${{secrets.SECRET_MY_TOKEN}}@github.com/kentaro19781123/filedl.git

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: install
      run: npm ci

#     - name: add env.production
#       run: |
#         touch .env.production
#         echo "API_KEY=${{ secrets.SECRET_MICRO_API }}" >> .env.production
    - name: build
      run: node dl
      # run: echo "${{ toJSON(github.event.client_payload) }}"

    - name: save image
      uses: actions/upload-artifact@v2
      with:
        name: image
        # path: ./image
        path: ${{ github.workspace }}/image

    - name: commit artifact and push
      run: |
        git config --global user.email "kens19781123@gmai.com"
        git config --global user.name "kentaro19781123"
        git status
        git add .
        git commit -m "画像追加"
        git branch
        # git push ${REPO} HEAD:main || true