name: test

on:
  # workflow_dispatch:
  push:
    branches:
      - test

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Val
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: "Asia/Tokyo"
        run: echo "TITLE2=[DEVELOP]$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        run: gh pr create --head test -B test2 -t ${{ env.TITLE2 }} -b ""

  result_success:
    if: success()
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
      - name: Set Val
        run: echo "成功しました"

  result_Failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
      - name: Set Val
        run: echo "失敗しました"
