name: test

on:
  # workflow_dispatch:
  push:
    branches:
      - test

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Val
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: "Asia/Tokyo"
        run: echo "TITLE2=[DEVELOP]$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        run: gh pr create --head test -B test2 -t ${{ env.TITLE2 }} -b ""
